name: Lint .NET Code

on:
  push:

jobs:
  lint:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # Install .NET Code Quality Analyzer tools
    - name: Install dotnet format
      run: dotnet tool install --global dotnet-format

    # Run the linting process
    - name: Run code formatter
      run: dotnet format --verify-no-changes
